1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [42]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [43]:
import pandas as pd
import numpy as np
zp = np.array(zp)
ks = np.array(ks)

In [44]:
kovariz = np.mean(zp*ks) - np.mean(zp)* np.mean(ks)
kovariz

9157.839999999997

In [45]:
cov_0 = np.cov(zp,ks, ddof=0)
cov_0

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [46]:
cov_1 = np.cov(zp,ks, ddof=1)
cov_1

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [47]:
pirs = cov_0/(np.std(zp)*np.std(ks))
pirs

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [48]:
pirson = np.corrcoef(zp, ks)
pirson

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2.Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.



In [49]:
alfa = 1 - 0.95
data = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]
n = len(data) 
n_sred =  sum(data) / len(data)
import pandas as pd
# import numpy as np
data = pd.DataFrame(data)

t = 2.262
alpha2 = 0.05/2
std = data.std(ddof=1)

n_sred , n, alpha2, t, std

(118.1,
 10,
 0.025,
 2.262,
 0    10.545668
 dtype: float64)

In [50]:
dover_nizg = n_sred - t *(std/((n)**0.5))
dover_verh = n_sred + t *(std/((n)**0.5))
dover_nizg, dover_verh

(0    110.556608
 dtype: float64,
 0    125.643392
 dtype: float64)

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [51]:
std = 5
dispers = 25
n = 27
mu = 174.2

alpha2 = 0.05/2

In [52]:
z_tabl = 1.96

In [53]:
dover_nizg = mu - (z_tabl*std/(n)**0.5)
dover_verh = mu + (z_tabl*std/(n)**0.5)
dover_nizg, dover_verh

(172.31398912064722, 176.08601087935276)